---


- hosts: devlinux
  user: pradip
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:

    - name: install httpd
      action: yum pkg=httpd state=present

    - name: start https
      action: service name=httpd state=started

    - name: copy
      action: copy src=/mnt/project/index.html dest=/var/www/html/
      
    - name: permission
      command: chmod 777 /var/www/html/index.html
