---


- hosts: devlinux
  user: pradip
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:

    - name: install httpd
      action: yum pkg=httpd state=present

    - name: start https
      action: service name=httpd state=started

    - name: permission
      ansible.builtin.file:
        path: /var/www/html/index.html
        mode: '0644'
